### ISSUE TITLE
No Longer Works

### ISSUE THREAD

**Issue by SourCandy80** [antunnitraj/ATLauncher-Offline-Bypass#2]
Account just doesnt show up in the account selector.

**Comment by antunnitraj** [comment]
Please tell me what version are you using (Installer/Portable/Flatpak) + what OS (Linux/Windows).

**Comment by SourCandy80** [comment]
I guess that means im doing something wrong. I executed the script (had to change path to `data/config` instead of `config`

Im using the installed version from the Linux Mint software manager. Latest version of ATLauncher.

**Comment by SourCandy80** [comment]
/home/egoist/.var/app/com.atlauncher.ATLauncher/data/configs/

my path ^

**Comment by antunnitraj** [comment]
try removing the accounts.json file with this command
```
rm ~/.var/app/com.atlauncher.ATLauncher/data/configs/accounts.json
```

Then installing it again with this command:
```
echo '[{"accessToken":"0","mustLogin":true,"username":"00000000-0000-0000-0000-000000000000","minecraftUsername":"YOURUSERNAMEHERE","uuid":"00000000000000000000000000000000","collapsedPacks":[],"collapsedInstances":[],"collapsedServers":[],"internalType":"com.atlauncher.data.MicrosoftAccount"}]' > ~/.var/app/com.atlauncher.ATLauncher/data/configs/accounts.json
```

And then relaunch ATLauncher.

**Comment by SourCandy80** [comment]
Done.
![image](https://github.com/antunnitraj/ATLauncher-Offline-Bypass/assets/111071796/814e8b65-052a-47d5-92e0-c9d20e6a6fc5)

**Comment by SourCandy80** [comment]
I need the application closed correct?

**Comment by antunnitraj** [comment]
Yes, close ATLauncher, execute the removal script that i typed and install the patch again.
I am currently trying it out locally.

**Comment by SourCandy80** [comment]
Yes that is what i did. I logged into a microsoft account before doing any of this if that has any effect on anything.

**Comment by antunnitraj** [comment]
I don't think it has any effect because it overrides the whole file. Give me a minute, i just installed ATLauncher.

**Comment by SourCandy80** [comment]
> I don't think it has any effect because it overrides the whole file. 

Thought so. Also understood.

**Comment by SourCandy80** [comment]
Just to be clear I have the "flathub" version installed.

**Comment by antunnitraj** [comment]
You are right, they patched it, thank you for informing me :)
I will now archive this repo until i found a new way.

If you want an alternative feel free to use my PrismLauncher bypass here: https://github.com/antunnitraj/Prism-Launcher-PolyMC-Offline-Bypass
